# Q1: Import numpy library

In [18]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [19]:
# write your code here ^_^
sequence = np.linspace(1.0, 5.0, 15)
sequence

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [20]:
# write your code here ^_^
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])
array_3d = np.array([[arr1], [arr2], [arr3], [arr4]])
array_3d

array([[[ 1.1,  2.1,  3.1]],

       [[ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1]],

       [[10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [21]:
# write your code here ^_^
print("Array's type:", type(array_3d))
print("Array's elements datatype:", array_3d[0, 0, 0].dtype)
print("Array's shape:", array_3d.shape)
print("Array's size:", array_3d.size)
print("Array's dimension:", array_3d.ndim)

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (4, 1, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes.
- Print the new array's dimention and shape.

In [22]:
# write your code here ^_^
new_array_4d = array_3d[np.newaxis, ...]
print("New array's dimension:", new_array_4d.ndim)
print("New array's shape:", new_array_4d.shape)

New array's dimension: 4
New array's shape: (1, 4, 1, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes.
- Print the new array.

In [23]:
# write your code here ^_^
new_array_int = new_array_4d.astype(int)
print("New array with integer datatype:")
print(new_array_int)

New array with integer datatype:
[[[[ 1  2  3]]

  [[ 4  5  6]]

  [[ 7  8  9]]

  [[10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [24]:
# write your code here ^_^
print("Printing all array's elements:")
for element in np.nditer(new_array_int):
    print(element, end=" ")
print()

Printing all array's elements:
1 2 3 4 5 6 7 8 9 10 11 12 


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [25]:
# write your code here ^_^
print("Number 8:", new_array_int[0, 1, 0, 1])

Number 8: 5


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [26]:
# write your code here ^_^
print("Number 5 and number 6:")
print(new_array_int[0, :, 0, 1])

Number 5 and number 6:
[ 2  5  8 11]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [27]:
# write your code here ^_^
indices = np.where(new_array_int == 8)
print("Indices leading to number 8:")
print(indices)

Indices leading to number 8:
(array([0]), array([2]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [28]:
# write your code here ^_^
reshaped_array = new_array_int.reshape((2, 3, 2))
print("Reshaped array:")
print(reshaped_array)

Reshaped array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis

In [29]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2))

print("Joined arrays without specifying axis:")
print(joined_array)

Joined arrays without specifying axis:
[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1

In [30]:
# write your code here ^_^

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])


joined_array_rows = np.hstack((arr1, arr2))

print("Joined arrays along rows:")
print(joined_array_rows)

Joined arrays along rows:
[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.
Note: use the same array from Q12.1

In [31]:
# write your code here ^_^

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

split_arr1 = np.array_split(arr1, 2, axis=1)
split_arr2 = np.array_split(arr2, 2, axis=1)

print("Split arrays:")
for arr in split_arr1:
    print(arr)
print()
for arr in split_arr2:
    print(arr)

Split arrays:
[['A']
 ['E']]
[['B']
 ['F']]

[['C']
 ['G']]
[['D']
 ['H']]
