# Q1: Import numpy library

In [4]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [5]:
np.linspace(1,15,15)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [10]:
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])

arr_3d = np.array([[arr1,arr2],[arr3,arr4]])
print(arr_3d.shape)


(2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [7]:
print("Array's type:", type(arr_3d))
print("Array's elements datatype:", arr_3d.dtype)
print("Array's shape:", arr_3d.shape)
print("Array's size:", arr_3d.size)
print("Array's dimension:", arr_3d.ndim)


Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [11]:
arry_4d = arr_3d.reshape(1,2,2,3)

print("Array's dimension: ", arry_4d.ndim)
print(arry_4d.shape)

Array's dimension:  4
(1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [16]:
arr_4d = np.array(arr_3d,dtype =int)
print(arr_4d_int)
print("Array's elements datatype:", arr_4d.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array's elements datatype: int32


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [22]:
it = np.nditer(arr_4d)
for element in it:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [56]:
print(arr_4d[1,0,1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [55]:
print(arr_4d[0,1,1:3])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [64]:
np.where(arr_4d == 8)

(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [66]:
arr_4d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [75]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
HA = np.hstack((arr1,arr2))
HA

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [78]:
VA = np.vstack((arr1,arr2))
VA

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [88]:
a1,a2 = np.hsplit(VA,2)
print(a1)
print(a2)


[['A']
 ['E']
 ['C']
 ['G']]
[['B']
 ['F']
 ['D']
 ['H']]
