# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [14]:
arr = np.linspace(0, 15, num=15)
arr

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [16]:
arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

array = np.array([arr1, arr2, arr3, arr4])
array


array([[ 1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1],
       [ 7.1,  8.1,  9.1],
       [10.1, 11.1, 12.1]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [21]:
print('array type:', type(array))
print('data type = ', array.dtype)
print('shape = ', array.shape)
print('size = ', array.size)
print('dimention = ', array.ndim)



array type: <class 'numpy.ndarray'>
data type =  float64
shape =  (4, 3)
size =  12
dimention =  2


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [24]:
newArray = array.copy()
fdArray = newArray.reshape(2, 2, 3, 1)
fdArray

array([[[[ 1.1],
         [ 2.1],
         [ 3.1]],

        [[ 4.1],
         [ 5.1],
         [ 6.1]]],


       [[[ 7.1],
         [ 8.1],
         [ 9.1]],

        [[10.1],
         [11.1],
         [12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [27]:
intArray = fdArray.copy()
intArray = intArray.astype(int)
intArray

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [30]:
for i in np.nditer(intArray):
 print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [48]:
number8 = intArray[1, 0, 1, 0] 
number8

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [66]:
number5 = intArray[0, 1, 1, 0] 
print(number5)
number6 = intArray[0, 1, 2, 0] 
print(number6)

5
6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [73]:
where8 = np.where(intArray == 8)
where8

(array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [74]:
intArray.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [75]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
joined= np.concatenate((arr1,arr2))
joined

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [76]:
joinedAx1= np.concatenate((arr1,arr2), axis=1)
joinedAx1

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [77]:
splited = np.split(joined, 2, axis=1)
splited

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]