# Q1: Import numpy library

In [4]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [5]:
sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [14]:
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])
# arr2d = np.array([arr1, arr2, arr3, arr4])
arr3d = np.array([[arr1, arr2], [arr3, arr4]]) # also arr2d.reshape(2, 2, 3)
print(arr3d.shape,'\n')
print(arr3d)



(2, 2, 3) 

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [17]:
print(type(arr3d))
print(arr3d.dtype)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [20]:
arr4d = arr3d.reshape(4,1,3)
print(arr4d)

[[[ 1.1  2.1  3.1]]

 [[ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]]

 [[10.1 11.1 12.1]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [27]:
intArr4d = arr4d.astype(int)
print(intArr4d)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [28]:

for x in np.nditer(intArr4d):
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [29]:
print(intArr4d[2, 0, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [31]:
print(intArr4d[1, 0, 1])
print(intArr4d[1, 0, 2])

5
6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [60]:
indecies = np.where(intArr4d == 8)

print('({}, {}, {})'.format(indecies[0][0], indecies[1][0], indecies[2][0]))





(2, 0, 1)


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [62]:
print(intArr4d.reshape(2, 3, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [76]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr12 = np.concatenate((arr1, arr2))
print(arr12)


[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [73]:
arr12_2 = np.concatenate((arr1, arr2), axis=1)
print(arr12)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [78]:
arr13 = np.split(arr12, 2, axis=1)
print(arr13)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
