# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [4]:
sequence=np.linspace(0.0, 1.0 , 15)
sequence

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [2]:
array1 = np.array([1.1 , 2.1 , 3.1])
array2 = np.array([4.1 , 5.1 , 6.1])
array3 = np.array([7.1 , 8.1 , 9.1])
array4 = np.array([10.1 , 11.1 , 12.1])
three_d_arr=np.array([array1,array2,array3,array4])

three_d_arr


array([[ 1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1],
       [ 7.1,  8.1,  9.1],
       [10.1, 11.1, 12.1]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [9]:
three_d_arr.shape

(4, 3)

In [10]:
three_d_arr.ndim

2

In [11]:
three_d_arr.size

12

In [12]:
three_d_arr.dtype

dtype('float64')

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [8]:
array_4d = three_d_arr.reshape((1, 4, 3, 1))
array_4d

array([[[[ 1.1],
         [ 2.1],
         [ 3.1]],

        [[ 4.1],
         [ 5.1],
         [ 6.1]],

        [[ 7.1],
         [ 8.1],
         [ 9.1]],

        [[10.1],
         [11.1],
         [12.1]]]])

In [9]:
array_4d.ndim

4

In [10]:
array_4d.shape

(1, 4, 3, 1)

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [12]:
new_int_array=array_4d.astype(int)
new_int_array

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]],

        [[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [13]:
for i in np.nditer(new_int_array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [16]:
x = new_int_array[0, 2, 1, 0]
x

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [18]:
y = new_int_array[0, 1, 1, 0]
y

5

In [19]:
z = new_int_array[0, 1, 2, 0]
z

6

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [20]:
position = np.where(new_int_array == 8)
position

(array([0], dtype=int64),
 array([2], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [22]:
array_reshaped = new_int_array.reshape(2, 3, 2)
array_reshaped

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [24]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
join_a = np.concatenate((arr1, arr2))
join_a

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [26]:
join_b = np.concatenate((arr1, arr2), axis=1)
join_b

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [29]:
array1, array2 = np.hsplit(join_a, 2)
array1

array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1')

In [30]:
array2

array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')