# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [3]:
#Q2
flo = np.linspace(0,1,15)
print(flo)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:
#Q3
arr1=[1.1,2.1,3.1]
arr2=[4.1,5.1,6.1]
arr3=[7.1,8.1,9.1]
arr4=[10.1,11.1,12.1]

_3D = np.array([
    [arr1, arr2],
    [arr3, arr4]
])
print(_3D)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [5]:
#Q4
print(f'type : {type(_3D)}')
print(f'element data type : {_3D.dtype}')
print(f'Shape: {_3D.shape}')
print(f'Size :{_3D.size}')
print(f'number of dimensions: {_3D.ndim}')

type : <class 'numpy.ndarray'>
element data type : float64
Shape: (2, 2, 3)
Size :12
number of dimensions: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [6]:
#Q5
_4D = np.expand_dims(_3D, axis=0)
print(_4D.ndim)
print(_4D.shape)

4
(1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [7]:
#Q6
int_arr=_4D.astype(int)
print(int_arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [8]:
#Q7
for x in np.nditer(int_arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [9]:
#Q8
print(f'eight: {int_arr[0,1,0,1]}')

eight: 8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [10]:
#Q9
print(f'five: {int_arr[0,0,1,1]}')
print(f'six: {int_arr[0,0,1,2]}')

five: 5
six: 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [11]:
#Q10
print(np.where(int_arr == 8))

(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [12]:
#Q11
q11=int_arr.reshape((2,3,2))
print(q11)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [13]:
#Q12
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
#Q12.1
joined_arr = np.concatenate([arr1, arr2])
print(joined_arr)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [14]:
#Q12.2
joined_arr_ax=np.concatenate((arr1, arr2), axis=1)
print(joined_arr_ax)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [15]:
#Q13
sp=np.split(joined_arr,2,axis=1)
print(sp)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
